config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  resources :appointments, only: :index
  # get /appointments, to: 'appointments#index'

  resources :houses, only: %i[index show]
  # ^ This command creates the same routes as the following two:
  # get '/houses', to: 'houses#index'
  # get '/houses/:id', to: 'houses#show', id: /\d+/

  resources :students, only: :show
  # get '/students/:id', to: 'students#show', id: /\d+/

  resources :teachers, only: :show
  # get '/teachers/:id', to: 'teachers#show', id: /\d+/

  root to: 'houses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :student
  belongs_to :teacher

  validates :scheduled, presence: true
end

app/models/house.rb
# frozen_string_literal: true

class House < ApplicationRecord
  has_many :students
  has_many :teachers

  validates :name, :points, presence: true
  validates :points, numericality: { only_integer: true }
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :teachers, through: :appointments

  validates :name, presence: true
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :students, through: :appointments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  def index
    @houses = House.order(:name)
  end
  # Automagically load up the associated view.
  # app/views/houses/index.html.erb
  # All instance variables are shared with the view.

  def show
    @house = House.find(params[:id])
  end
  # Automagically load up the associated view.
  # app/views/houses/show.html.erb
  # This view will get access to the @house variable.
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  http_basic_authenticate_with(
    name: 'fullstack',
    password: 'toomanysecrets!',
    except: :permalink
  )

  before_action :set_page, only: %i[show edit update destroy]

  # GET /static/:permalink
  def permalink
    @page = Page.find_by_permalink(params[:permalink])

    if @page
      render :show # /app/views/pages/show.html.erb
    else
      redirect_to root_path
    end
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  def show
    @student = Student.find(params[:id])
  end
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  def show
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<% if @appointments.empty? %>
  <p>There are no appointments.</p>
<% else %>
  <ul>
  <% @appointments.each do |appointment| %>
    <li>
      <%= link_to appointment.teacher.name, appointment.teacher %> will be meeting with
      <%= link_to appointment.student.name, appointment.student %> on <%= appointment.scheduled %>.
    </li>
  <% end %>
  </ul>
<% end %>

app/views/houses/index.html.erb
<h1>Hogwarts School for Wiiiiiiizards</h1>

<% @houses.each do |house| %>
  <h2><%= house.name %></h2>
  <p>This house has <%= pluralize house.points, 'point' %>.</p>
  <p>For a list of students in this house, <%= link_to 'click here', house %>.</p>
<% end %>

app/views/houses/show.html.erb
<h2><%= @house.name %></h2>

<p>This house has <%= pluralize @house.points, 'point' %>.</p>
<h3>Students</h3>
<ul>
  <% @house.students.each do |student| %>
    <li><%= link_to student.name, student %></li>
  <% end %>
</ul>

<h3>Teachers</h3>
<ul>
  <% @house.teachers.each do |teacher| %>
    <li><%= link_to teacher.name, teacher %></li>
  <% end %>
</ul>

<p><%= link_to 'Home', root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HogwartsOnRailsNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Appointments', appointments_path %></li>
          <li><%= link_to 'About', permalink_path(permalink: 'about_us') %></li>
          <li><%= link_to 'FAQ', permalink_path(permalink: 'faq') %></li>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @page.title %>
</h1>

<p>
  <%= @page.content %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>

<p>This student belongs to house <%= link_to(@student.house.name, @student.house) %>.</p>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>

<p>
  <%= @teacher.name %> belongs to house
  <%= link_to @teacher.house.name, @teacher.house%> and
  they have <%= pluralize @teacher.appointments.size, 'appointment' %>.
</p>